M48
; DRILL file {KiCad 9.0.7} date 2026-04-02T00:49:18+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-02T00:49:18+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X116.25Y-108.0
X117.25Y-158.75
X169.0Y-151.85
X185.0Y-157.5
M30
